# Generated by Django 2.1 on 2018-08-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('instagram', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('facebookURL', models.URLField()),
                ('campaignUrl', models.URLField()),
                ('supportUrl', models.URLField()),
                ('age', models.PositiveIntegerField()),
                ('electedBefore', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Party'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Picture'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Role'),
        ),
    ]
