# Generated by Django 2.1 on 2018-08-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField()),
                ('party', models.TextField()),
                ('number', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
            ],
        ),
    ]
