# Generated by Django 2.1 on 2018-08-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('instagram', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('facebookURL', models.URLField()),
                ('campaignUrl', models.URLField()),
                ('supportUrl', models.URLField()),
                ('age', models.PositiveIntegerField()),
                ('electedBefore', models.BooleanField(default=False)),
            ],
        ),
    ]
