# Generated by Django 2.1 on 2018-08-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
