# Generated by Django 2.1 on 2018-08-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.Party'),
        ),
    ]
