# Generated by Django 2.1 on 2018-08-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_genderidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='causes',
            field=models.ManyToManyField(to='candidates.Cause'),
        ),
    ]
