# Generated by Django 2.1 on 2018-08-11 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_add_causes_to_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='candidates.Picture'),
        ),
    ]
