# Generated by Django 2.1 on 2018-08-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_create_ethnicity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='electionName',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='genderIdentity',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='candidates.GenderIdentity'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='previousRole',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='previous_role',
                to='candidates.Role'),
        ),
    ]
