# Generated by Django 2.1 on 2018-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_review_models_add_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={
                'verbose_name': 'Candidata',
                'verbose_name_plural': 'Candidatas'
            },
        ),
        migrations.AlterModelOptions(
            name='cause',
            options={
                'verbose_name': 'Causa',
                'verbose_name_plural': 'Causas'
            },
        ),
        migrations.AlterModelOptions(
            name='ethnicity',
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias'
            },
        ),
        migrations.AlterModelOptions(
            name='genderidentity',
            options={
                'verbose_name': 'Identidade de Gênero',
                'verbose_name_plural': 'Identidades de Gênero'
            },
        ),
        migrations.AlterModelOptions(
            name='party',
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos'
            },
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos'
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos'
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='campaignUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='facebookUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='instagram',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='supportUrl',
            field=models.URLField(blank=True),
        ),
    ]
